const shynessScaleQuestionData = [
  {
    question: "اناشخص خجول",
    answerOne: "موافق بشدة",
    answerTwo: "موافق",
    answerThree: "محايد",
    answerFour: "لا أوافق",
    answerFive: "لا أوافق بشدة",
  },
  {
    question: "الاخرون يعتقدون أنني أتحدث كثيرا",
    answerOne: "موافق بشدة",
    answerTwo: "موافق",
    answerThree: "محايد",
    answerFour: "لا أوافق",
    answerFive: "لا أوافق بشدة",
  },
  {
    question: "أنا شخص كثير الكلام",
    answerOne: "موافق بشدة",
    answerTwo: "موافق",
    answerThree: "محايد",
    answerFour: "لا أوافق",
    answerFive: "لا أوافق بشدة",
  },
  {
    question: "الاخرون يعتقدون أنني شخص خجول",
    answerOne: "موافق بشدة",
    answerTwo: "موافق",
    answerThree: "محايد",
    answerFour: "لا أوافق",
    answerFive: "لا أوافق بشدة",
  },
  {
    question: "عادة ما أتحدث كثيرا",
    answerOne: "موافق بشدة",
    answerTwo: "موافق",
    answerThree: "محايد",
    answerFour: "لا أوافق",
    answerFive: "لا أوافق بشدة",
  },
  {
    question: "عادة ما أكون هادئ في الفصل الدراسي",
    answerOne: "موافق بشدة",
    answerTwo: "موافق",
    answerThree: "محايد",
    answerFour: "لا أوافق",
    answerFive: "لا أوافق بشدة",
  },
  {
    question: "لا أتحدث كثيرا",
    answerOne: "موافق بشدة",
    answerTwo: "موافق",
    answerThree: "محايد",
    answerFour: "لا أوافق",
    answerFive: "لا أوافق بشدة",
  },
  {
    question: "أتحدث عادة أكثر من الاخرين",
    answerOne: "موافق بشدة",
    answerTwo: "موافق",
    answerThree: "محايد",
    answerFour: "لا أوافق",
    answerFive: "لا أوافق بشدة",
  },
  {
    question: "اناشخص هادئ",
    answerOne: "موافق بشدة",
    answerTwo: "موافق",
    answerThree: "محايد",
    answerFour: "لا أوافق",
    answerFive: "لا أوافق بشدة",
  },
  {
    question: "عادة ما أاحدث عند مجموعات صغيرة 6-3 أشخاص",
    answerOne: "موافق بشدة",
    answerTwo: "موافق",
    answerThree: "محايد",
    answerFour: "لا أوافق",
    answerFive: "لا أوافق بشدة",
  },
  {
    question: "معظم الأشخاص يتحدثون اكثر مما أفعل",
    answerOne: "موافق بشدة",
    answerTwo: "موافق",
    answerThree: "محايد",
    answerFour: "لا أوافق",
    answerFive: "لا أوافق بشدة",
  },
  {
    question: "أتحدث في الفصل أكثر مما يفعل الأخرون",
    answerOne: "موافق بشدة",
    answerTwo: "موافق",
    answerThree: "محايد",
    answerFour: "لا أوافق",
    answerFive: "لا أوافق بشدة",
  },
  {
    question: "في الغالب الناس عادة أكثر خجلا مني ",
    answerOne: "موافق بشدة",
    answerTwo: "موافق",
    answerThree: "محايد",
    answerFour: "لا أوافق",
    answerFive: "لا أوافق بشدة",
  },

  // {
  //     question:'اناشخص خجول',
  //     answerOne:['موافق بشدة','موافق','محايد','لا أوافق','لا أوافق بشدة']
  // }
];
export default shynessScaleQuestionData;
