import Head from "next/head";
import data from "../allQuiz";
import styles from "../styles/Home.module.css";
import MySlide from "../components/Slides/MySlide";
import ModalShyness from "../components/ModalShynees/ModalShyness";
import { useRouter } from "next/router";

export default function Home(props) {
  const { locale } = useRouter();

  // console.log(JSON.parse(props.rowData)[locale]);
  return (
    <div className={styles.container}>
      <Head>
        <title>Scales</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <MySlide data={props.rowData} />
      </main>
    </div>
  );
}

export async function getStaticProps() {
  const rowData = JSON.stringify(data);
  return {
    props: { rowData },
  };
}
