import Head from "next/head";

import styles from "../styles/Home.module.css";
import MySlide from "../components/Slides/MySlide";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Scales</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <MySlide />
      </main>
    </div>
  );
}
